In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

dataset = pd.read_csv('cars.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
display(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.8, random_state = 0)

regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

np.set_printoptions(precision=2)

display(np.concatenate((y_pred.reshape(len(y_pred), 1),y_test.reshape(len(y_test), 1) ), 1))

array([[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2000, 312313,
        11, 105066, 105, 0, 0, 5],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2005, 334297,
        30, 24726, 90, 1, 1, 3],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2007, 456423,
        10, 55034, 59, 1, 0, 3],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 2019, 521410,
        11, 177543, 110, 1, 0, 5],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2007, 360705,
        21, 123976, 96, 1, 1, 3],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 2011, 409126,
        22, 83185, 109, 0, 1, 3],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2012, 556760,
        20, 180990, 97, 0, 0, 3],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2000, 379202,
        30, 100805, 91, 0, 1, 3],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2018, 417357,
        10, 57922, 91, 1, 1, 3],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

array([[219944.82, 219701.  ],
       [263515.7 , 263717.  ],
       [393421.84, 393139.5 ],
       [287272.41, 287877.  ],
       [312632.77, 312097.5 ],
       [239092.52, 238906.5 ],
       [399723.17, 399830.  ],
       [390334.53, 390193.  ],
       [328691.3 , 328799.5 ],
       [512546.6 , 512402.5 ],
       [351531.51, 351630.  ],
       [387675.12, 387128.5 ],
       [284604.9 , 284469.  ],
       [527461.6 , 527394.  ],
       [252989.66, 252974.5 ],
       [394192.13, 393906.  ],
       [501597.61, 501950.  ],
       [307407.83, 307093.  ],
       [325592.76, 325340.  ],
       [599799.  , 600276.  ],
       [520520.22, 520486.  ],
       [589310.24, 589875.  ],
       [544575.37, 544950.  ],
       [531968.61, 531674.5 ],
       [424657.22, 424624.  ],
       [298606.7 , 298396.  ],
       [358317.76, 358442.5 ],
       [413373.89, 412678.5 ],
       [312280.41, 312533.5 ],
       [490130.24, 489761.5 ],
       [256689.83, 257280.  ],
       [298168.7 , 298819.5 ],
       [

In [16]:

display(regressor.predict([[1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2010,500000,20,250000,80,1,0,3]]))


array([324820.52])